"""clinical domain

Revision ID: 8d7590d48592
Revises: 6b1ad8a5c6c1
Create Date: 2026-10-05 17:01:01.929944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d7590d48592'
down_revision: Union[str, Sequence[str], None] = '6b1ad8a5c6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('term', sa.String(length=40), nullable=False),
    sa.Column('rubric_file_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', name=op.f('uq_courses_code'))
    )
    op.create_table('course_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('discipline_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_memberships_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_course_memberships_discipline_id_disciplines')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_course_memberships_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_memberships')),
    sa.UniqueConstraint('user_id', 'course_id', 'role_id', name='uq_membership_user_course_role')
    )
    op.create_index(op.f('ix_course_memberships_course_id'), 'course_memberships', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_memberships_user_id'), 'course_memberships', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex_at_birth', sa.String(length=20), nullable=False),
    sa.Column('pronouns', sa.String(length=40), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('case_key', sa.String(length=50), nullable=False),
    sa.Column('source_patient_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('practice_label', sa.String(length=80), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('hpi', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.String(length=40), nullable=False),
    sa.Column('encounter_status', sa.String(length=40), nullable=False),
    sa.Column('care_setting', sa.String(length=40), nullable=False),
    sa.Column('program', sa.String(length=80), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=False),
    sa.Column('surgical_history', sa.Text(), nullable=False),
    sa.Column('social_history', sa.Text(), nullable=False),
    sa.Column('insurance_payer', sa.String(length=120), nullable=True),
    sa.Column('insurance_member_id', sa.String(length=60), nullable=True),
    sa.Column('insurance_group_number', sa.String(length=60), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=40), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=60), nullable=True),
    sa.Column('is_training', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_patients_course_id_courses')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_patients_owner_id_users')),
    sa.ForeignKeyConstraint(['source_patient_id'], ['patients.id'], name=op.f('fk_patients_source_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('mrn', name=op.f('uq_patients_mrn'))
    )
    op.create_index(op.f('ix_patients_course_id'), 'patients', ['course_id'], unique=False)
    op.create_index(op.f('ix_patients_owner_id'), 'patients', ['owner_id'], unique=False)
    op.create_table('allergies',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('substance', sa.String(length=120), nullable=False),
    sa.Column('reaction', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_allergies_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergies'))
    )
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('when', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('with_whom', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_encounters_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters')),
    sa.UniqueConstraint('patient_id', name=op.f('uq_encounters_patient_id'))
    )
    op.create_table('lab_results',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reference_range', sa.String(length=40), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=True),
    sa.Column('collected_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_lab_results_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_results'))
    )
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose', sa.String(length=60), nullable=False),
    sa.Column('route', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=80), nullable=False),
    sa.Column('indication', sa.String(length=120), nullable=True),
    sa.Column('adherence', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medications_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('problems',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('since', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_problems_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_patient_id'), 'problems', ['patient_id'], unique=False)
    op.create_table('referrals',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('to_discipline_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_referrals_created_by_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_referrals_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_discipline_id'], ['disciplines.id'], name=op.f('fk_referrals_to_discipline_id_disciplines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_table('vitals',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vitals_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vitals'))
    )
    op.create_index(op.f('ix_vitals_patient_id'), 'vitals', ['patient_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('discipline_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnoses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routed_to_id', sa.Uuid(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cosigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cosigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_clinical_notes_author_id_users')),
    sa.ForeignKeyConstraint(['cosigned_by_id'], ['users.id'], name=op.f('fk_clinical_notes_cosigned_by_id_users')),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name=op.f('fk_clinical_notes_discipline_id_disciplines')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_clinical_notes_encounter_id_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_notes_patient_id_patients')),
    sa.ForeignKeyConstraint(['routed_to_id'], ['users.id'], name=op.f('fk_clinical_notes_routed_to_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_notes'))
    )
    op.create_index(op.f('ix_clinical_notes_author_id'), 'clinical_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_routed_to_id'), 'clinical_notes', ['routed_to_id'], unique=False)
    op.create_table('note_addenda',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_note_addenda_author_id_users')),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_note_addenda_note_id_clinical_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_addenda'))
    )
    op.create_index(op.f('ix_note_addenda_note_id'), 'note_addenda', ['note_id'], unique=False)
    op.create_table('note_comments',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_note_comments_author_id_users')),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_note_comments_note_id_clinical_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_comments'))
    )
    op.create_index(op.f('ix_note_comments_note_id'), 'note_comments', ['note_id'], unique=False)
    op.add_column('audit_events', sa.Column('result', sa.String(length=10), server_default='ok', nullable=False))
    op.add_column('audit_events', sa.Column('course_id', sa.Uuid(), nullable=True))
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_events_course_id'), 'audit_events', ['course_id'], unique=False)
    op.create_foreign_key(op.f('fk_audit_events_course_id_courses'), 'audit_events', 'courses', ['course_id'], ['id'])
    op.add_column('users', sa.Column('university_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_last4', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_last4')
    op.drop_column('users', 'university_id')
    op.drop_constraint(op.f('fk_audit_events_course_id_courses'), 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_course_id'), table_name='audit_events')
    op.alter_column('audit_events', 'action',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_events', 'course_id')
    op.drop_column('audit_events', 'result')
    op.drop_index(op.f('ix_note_comments_note_id'), table_name='note_comments')
    op.drop_table('note_comments')
    op.drop_index(op.f('ix_note_addenda_note_id'), table_name='note_addenda')
    op.drop_table('note_addenda')
    op.drop_index(op.f('ix_clinical_notes_routed_to_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_patient_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_author_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_vitals_patient_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_problems_patient_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_patients_owner_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_course_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_course_memberships_user_id'), table_name='course_memberships')
    op.drop_index(op.f('ix_course_memberships_course_id'), table_name='course_memberships')
    op.drop_table('course_memberships')
    op.drop_table('courses')
    # ### end Alembic commands ###
